### ISSUE TITLE
Error message when you forget to join the network first.

### ISSUE THREAD

**Issue by laduke** [zerotier/zeronsd#104]
Hi! Thanks for fixing that last one so fast. 

I was testing and kept seeing this:

```shell
sudo -E zeronsd start a84ac5c10a744c9d
INFO - Welcome to ZeroNS!
ERROR - error in response: status code 404 Not Found
```

The problem is I wasn't joined to a84ac5c10a744c9d. And for whatever reason my headspace didn't know what was obviously happening.

Do you think it should say something like "You need to join a84ac5c10a744c9d first" ? 

Just automatically joining a84ac5c10a744c9d for the user would be fancy, but probably too surprising. 

If yes, I will do the patch.

**Comment by erikh** [comment]
I think this is mostly resolved. Gonna close this, lmk if it's not.
