### ISSUE TITLE
Is ZeroNSd supposed to work with self-hosted  controller?

### ISSUE THREAD

**Issue by mcondarelli** [zerotier/zeronsd#107]
Hi, 
I'm trying to use ZeroNSd in a custom environment where I have a self-hosted ZT1 controller (and I use ZeroUI to interact with it, but that is another issue, I believe).

I am currently stuck with:
```
mcon@sid:~/projects/zeronsd/src$ /usr/sbin/zerotier-cli -T... listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks 8613c47a541ea8a2 testing-sid a2:2e:0d:90:00:90 OK PRIVATE zt7rd5vuxw 172.30.74.198/24
mcon@sid:~/projects/zeronsd/src$ ZEROTIER_CENTRAL_TOKEN="..." sudo -E /home/mcon/.cargo/bin/zeronsd start -v -v -s /var/lib/zerotier-one/authtoken.secret -d condarelli.it 8613c47a541ea8a2
INFO - Welcome to ZeroNS!
ERROR - error in response: status code 403 Forbidden
mcon@sid:~/projects/zeronsd/src$ 
```
I have several issues with this code (note: I do not know Rust, so I will have problems providing patches):
1. The obvious one: what's going wrong?
2. Apparently using the "verbose" flag has no effect (I hoped to get info about *which* request failed)
3. I can (actually *must*) provide ZEROTIER_CENTRAL_TOKEN, but there's no equivalent for `authtoken.secret`
4. Having (3) we could drop need for being `root` and use `setcap 'cap_net_bind_service+p' zeronsd` instead.

In general my real question is in Subject and also "how do I debug this?"

If it matters: I am currently using a VirtualBox VM based on Debian Sid for development. It has almost nothing installed but what's needed here to compile/debug/test ZeroTier-One, ZeroUI and ZeroNSd.

**Comment by mcondarelli** [comment]
As I suspected problem is ZeroNSd tries to unconditionally contact "https://my.zerotier.com/api/v1" which is obviously wrong if/when I use ZeroUI.
In my case that should be "http://localhost:3000/api/v1".
Is there an easy way to change/update that (besides the obvious code editing)?

**Comment by erikh** [comment]
We don't support emulated versions of central.

**Comment by mcondarelli** [comment]
I understand that, but the other questions still hold valid.

Note: my employer will not agree to use a tool relying on externally owned sites.
This has nothing to do with costs but it has a lot to do with fact anyone at ZeroTier Central can add any node to any network without "network owner" intervention or knowledge (I call it "paranoia", but I have little word in the matter).
Currently the only way (I know of) to circumvent problem is to move out from ZT Central and use a different "in house" site (basic ZT security model seems sound, but that cannot be said about ZT Central site, of course).
IMHO addressing such problems should be a ZT priority.

Many thanks for your good work (and patience)

**Comment by erikh** [comment]
I don't personally have any interest in this argument to continue it, and I am not in charge of Zerotier priorities and cannot change them.

If you don't like the solution the products are all covered under a BSD 3-Clause license.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by someara** [comment]
Hi Mcondarelli!

Currently, the local "raw" node controller API and the Central API are different enough that ZeroNSD will not work against it directly.

We are actively exploring ways to improve the self-hosted experience, but for now, ZeroNSD will only work against Central.

-s
