### ISSUE TITLE
Is there a way to run ZeroSND together with dnsmasq?

### ISSUE THREAD

**Issue by axel-verse** [zerotier/zeronsd#109]
My Ubuntu 20.04 VPS is modified to run without `systemd-resolved` due to `dnsmasq`. So is there a way to run ZeroSND together with `dnsmasq` and without `systemd-resolved`?

Using DNS forwarding via `dnsmasq` for `.zt` domain zone for example?

**Comment by laduke** [comment]
Hello,
zeronsd listens on a specific interface/address, one per zerotier network. You can tell dnsmasq to listen only on your physical address. I think that should work.

**Comment by erikh** [comment]
correct, zeronsd only listens on zerotier interfaces. It won't take over your whole machine.

If dnsmasq is listening on 0.0.0.0 however, you may run into trouble. Lock it down to specific bound addresses or interfaces instead.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by axel-verse** [comment]
Unfortunately, it doesn't. Dnsmasq conflicts with systemd-resolved due to exclusive 53 port binding. And (at my VPS) ZeroSND won't work with systemd-resolved stopped.

**Comment by erikh** [comment]
zeronsd doesn't require systemd-resolved. the client does.

**Comment by devvick** [comment]
@axel-verse
https://unix.stackexchange.com/questions/304050/how-to-avoid-conflicts-between-dnsmasq-and-systemd-resolved

> As of systemd 232 (released in 2017) you can edit `/etc/systemd/resolved.conf` and add this line:
> 
> ```
> DNSStubListener=no
> ```
> This will switch off binding to port 53.

**Comment by erikh** [comment]
I appreciate the energy but I'm fairly certain this isn't going to get the desired result. What might be best is to let systemd-resolved own the port and forward to dnsmasq *and* zeronsd.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by axel-verse** [comment]
@erikh thanks you, I tested your solution and it works for me. We can close the issue
