### ISSUE TITLE
[Feature request] Zone transfer to another DNS server

### ISSUE THREAD

**Issue by ieugen** [zerotier/zeronsd#110]
I would like to sync zerotier nodes to an existing DNS server

One way to do this is via zone transfer https://en.wikipedia.org/wiki/DNS_zone_transfer .

zeronsd would sync dns names from ZeroTier and then transfer them to an existing DNS server via zone transfer.

In this scenario, zeronsd is not used for resolving.

**Comment by erikh** [comment]
We've already nixed this feature, it's rife with security problems we don't want. The API can be used to solve your problem for this case.

**Comment by ieugen** [comment]
Can you please elaborate / share a link to the security issues you are referring to?
