### ISSUE TITLE
zeronsd works on all devices but iOS 15

### ISSUE THREAD

**Issue by thefactremains** [zerotier/zeronsd#111]
zeronsd  (with ZT one 1.6.6) works on all mac/windows devices, but not on my iOS15 device.

Immediately after upgrading to iOS 15, all the DNS broke - only on that device. This was on ZT 1.6.6 for iOS.

I have also confirmed that everything still works on another iOS 14 device on the same network (ZT 1.6.6)

**Comment by thefactremains** [comment]
I just discovered that disabling iCloud private relay fixes this issue.

**Comment by erikh** [comment]
oh. nice! Let's close this ticket then, now that it's recorded.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
