### ISSUE TITLE
ZeroNSD with other DNS providers

### ISSUE THREAD

**Issue by dbazina-dev** [zerotier/zeronsd#112]
Hello, 
this is not an issue, it's more like a question.
I would like to know is it possible to use ZeroNSD with the DNS server that is deployed inside LAN.
I want that ZeroNSD and local DNS use **same domain name**, so the desired behavior would be:

When I'm working from home, and I want to use some services from the office, I would use Zerotier network and ZeroNSD, but when I go to the office I want to use the DNS server from the office network. Is it possible to configure the network to work in that manner, it should be able to "detect" the network I'm using and then to redirect to the DNS on that network.
OS used for this are Debian 11 and Windows.

Thanks :)

**Comment by laduke** [comment]
Hi,
I think you should be able to get something to work. When you go in to work, turn off ("leave") that zerotier network. 
But I'd probably use different domains. like `app1.zt.domain` and `app1.domain`

**Comment by dbazina-dev** [comment]
Hello,
thanks for the answer. I've spent several days testing this use case.
So I managed to handle zeroDNS and local DNS together in Linux OS. There is a file named resolv.conf that is used for defining nameservers (IP address of the DNS servers) and the order of these nameservers defines which server will be "contacted first".

But, there is a problem with Windows 10. Whenever the "client" is connected to the ZeroTier network, and the checkbox AllowDNS is checked, it will always contact zeroNSD firstly. If I uncheck this checkbox, localDNS will be used first, but I would like to avoid that.

I've tried to change network interface order by changing the metric number, so I've put ZeroTier interface at 100, Wifi, and Ethernet were set to 10 (lower metric number means higher priority), but this didn't change the fact that zeroNSD is contacted first.
**Is this expected behavior on Windows, or there is some option that can change behavior?**
Thanks :)

**Comment by erikh** [comment]
I think you're going to run into issues unless you use different domain names. There are a lot of issues with this approach specifically with TLS that haven't even been tripped over yet in this conversation.
 
in summary, zeronsd is going to get the query if allowDNS is on or zerotier-systemd-manager is in play and you're connected to the network. There is no real workaround, as DNS resolvers are pretty bad at doing this without all the hacks we've piled on top to make it work. The best solution is to use two domain names, but the second best solution is to just disconnect from zerotier when you want to use the local DNS for that domain.

Sorry I don't have a better answer, but you can probably blame Jon Postel or Paul Vixie if you need someone to shake your fist at.

**Comment by erikh** [comment]
Closing this ticket, feel free to reopen or comment if you find a working solution for yourself.
