### ISSUE TITLE
Alpine/init.d OpenRC script

### ISSUE THREAD

**Issue by altano** [zerotier/zeronsd#123]
I didn't know where in the docs this should go, so I'll just leave it here.

Here's a working OpenRC init.d script you can use on Alpine (or other compatible systems). Just replace `<ZT-NETWORK>`, `<DOMAIN>`, and `<TOKEN>`:

/etc/init.d/zeronsd:
```
#!/sbin/openrc-run

depend() {
    need zerotier-one
    use network dns logger netmount
}

description="zeronsd for network <ZT-NETWORK>"
command="/root/.cargo/bin/zeronsd"
command_args="start
              --token <TOKEN>
              --wildcard
              --domain <DOMAIN>
              <ZT-NETWORK>"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"
```

Install zeronsd service to default runlevel with:
`rc-update add zeronsd`
(installing this will auto-start the zerotier-one service at boot as it is a hard dependency of zeronsd)

Start zeronsd service:
`rc-service zeronsd start`

**Comment by erikh** [comment]
if you know a bullet-proof way to detect alpine, we can add this to `zeronsd supervise` so we can just add it for users as a part of the commandline process.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by altano** [comment]
What are your long-term plans for packaging/distributing zerons? E.g. if you just plan on targeting and distributing for platforms, rather than doing this at runtime it might make sense to just _build_ the right functionality for different distros. Just a thought, as I'm no expert here.

**Comment by erikh** [comment]
We already package it for a variety of systems; take a peek at the makefile and `Dockerfile.packages` IIRC for more on this. There's also a readme on packaging cadence [here](https://github.com/zerotier/zeronsd/blob/main/docs/release.md) which goes into what I do to cut releases.

For alpine, I planned on making a container and an apk; `zeronsd supervise` already does a special build for macos and linux that twiddle launchd or systemd depending on platform; another switch for alpine-specific situations would be fine by me, as long as we could make it "just work" for users.
