### ISSUE TITLE
Clarify errors while reconciling names from Central

### ISSUE THREAD

**Issue by thefactremains** [zerotier/zeronsd#14]
No short names for nodes have space separators, but as soon as I add a node description with a space separator, I start to see this error and the DNS no longer resolves:

`error configuring authority: unrecognized char:`

When I remove the description, the issue resolves

**Comment by thefactremains** [comment]
disregard this, I had a node with a space in the short name and missed it

**Comment by erikh** [comment]
Let's leave this open as it could be much more obvious what the offensive record is and why it is offensive
