### ISSUE TITLE
Can't build on ArchLinux current (regex-syntax)

### ISSUE THREAD

**Issue by ato2** [zerotier/zeronsd#15]
Any clue ? ( I do not know rust)
cargo install --git https://github.com/zerotier/zeronsd --branch main
...........
   Compiling resolv-conf v0.7.0
   Compiling clap v2.33.3
   Compiling mime_guess v2.0.3
   Compiling url v2.2.2
   Compiling rand_chacha v0.3.0
error: could not compile `regex-syntax`
Caused by:
  process didn't exit successfully: `rustc --crate-name regex_syntax --edition=2018 /home/stud/stud/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.6.25/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="unicode"' --cfg 'feature="unicode-age"' --cfg 'feature="unicode-bool"' --cfg 'feature="unicode-case"' --cfg 'feature="unicode-gencat"' --cfg 'feature="unicode-perl"' --cfg 'feature="unicode-script"' --cfg 'feature="unicode-segment"' -C metadata=ba3e243391837928 -C extra-filename=-ba3e243391837928 --out-dir /tmp/cargo-installmNuNrh/release/deps -L dependency=/tmp/cargo-installmNuNrh/release/deps --cap-lints allow` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `zeronsd v0.1.0 (https://github.com/zerotier/zeronsd?branch=main#aa5b8c45)`, intermediate artifacts can be found at `/tmp/cargo-installmNuNrh`

**Comment by erikh** [comment]
Just built it on manjaro about an hour ago. Are you on a small server? Rust
will happily eat all your cpu and ram; check dmesg for oomkiller.

**Comment by ato2** [comment]
Yes I it was the reason ( I worked on small disk-less) with only 900M RAM free.
On bigger machine  builds OK.

**Comment by erikh** [comment]
Just putting a reminder here to put up binary releases. :)
