### ISSUE TITLE
ERROR trust_dns_server::store::in_memory::authority] could not lookup SOA for authority:

### ISSUE THREAD

**Issue by aleJohnny** [zerotier/zeronsd#153]
hi, i'm trying to setup zeronsd using docker, I followed the instructions, but can't get work and receive this message after run: 
Really don't know what to do...

$ sudo docker run --net host -it   -v /var/lib/zerotier-one/authtoken.secret:/authtoken.secret   -v /var/lib/zerotier-one/token:/token.txt -v /hosts-zeronsd:/hosts  zerotier/zeronsd:latest start -s /authtoken.secret -t /token.txt -f /hosts -d my.domain.tld 000000networkid0000

The output:

[2022-02-22T21:13:20Z ERROR trust_dns_server::store::in_memory::authority] could not lookup SOA for authority: mydomain.tld.
[2022-02-22T21:13:20Z ERROR trust_dns_server::store::in_memory::authority] could not lookup SOA for authority: my.domain.tld.
[2022-02-22T21:13:20Z ERROR trust_dns_server::store::in_memory::authority] could not lookup SOA for authority: 22.172.in-addr.arpa.
[2022-02-22T21:13:20Z ERROR trust_dns_server::store::in_memory::authority] could not lookup SOA for authority: 22.172.in-addr.arpa.

I tried with zeronsd:latest and zeronsd:alpine-latest images, same thing.

Am I missing something?

**Comment by erikh** [comment]
That's just an error coming from trust-dns, you can safely ignore it.

Please let me know if you are having trouble resolving domains on your tld.

**Comment by erikh** [comment]
I'll leave this open to try and quell these messages in the future.

**Comment by erikh** [comment]
I'm rushing to get 0.3.1 out tonight but hope to look into this early next week. Hope that helps.

**Comment by nooreldeensalah** [comment]
I've installed using the `.deb` package, and I'm getting the same error, using version `0.3.1`.
Should I downgrade to a lower version?

**Comment by aleJohnny** [comment]
> That's just an error coming from trust-dns, you can safely ignore it.
> 
> Please let me know if you are having trouble resolving domains on your tld.
So, i couldn't make work, unfortunately, but I think was something related to the node not direct connecting to other nodes (i saw the warning about latency), I was only able to relay the connections.
But I think it's a problem with the docker vm itself rather than zeronsd, because it was also routing ZT network to my LAN.

What I did was transfer the role to my opnsense router, installed ZT on it and now it's routing ZT to LAN and DNS with unbound.

I can ping every client in my LAN through ZT, but I can't ping my docker vm (in fact, it pings when is booting for 3 or 4 seconds and than stops, but I can ping from inside the LAN). Like I said, some issue with the docker VM.

But, i'll need setup zeronsd in another site where doesn't have a opnsense router and I'll back to you as far I installed again.

You can close the issue if you want!

Thanks for the help and thanks for the app!

**Comment by erikh** [comment]
I see the output of the log error as a bug (even if it results in no real error), so I'm leaving it open until I learn how to silence it. If you want to unsubscribe from the issue, feel free to.

**Comment by erikh** [comment]
@nooreldeensalah as indicated by the open status of this issue, it is not fixed yet. probably in a week or two.
