### ISSUE TITLE
`supervise` doesn't exit

### ISSUE THREAD

**Issue by laduke** [zerotier/zeronsd#154]
Hi, 
zeronsd 0.3.0, on debian

`supervise` doesn't print the systemd help message and it doesn't exit. Just hangs there. The .service file is created though.

**Comment by n2jwc** [comment]
have the same on Ubuntu 18 and 20. happy to provide any feedback necessary.

**Comment by erikh** [comment]
pretty sure I know what this is now. I have some evening business to attend to, but barring any further distractions I should have 0.3.1 out tonight which will fix it.

------- Original Message -------

**Comment by n2jwc** [comment]
Thanks Erik, it works now.  my pings to test are not but dig works.  weird.

**Comment by laduke** [comment]
Hey @n2jwc, are you on macOS? dig, nslookup, etc aren't hooked up to the OS's dns system... for some reason.

**Comment by n2jwc** [comment]
I did see that. However I was testing on the actual U I tu box I have setup
for zeronsd

**Comment by n2jwc** [comment]
> Hey @n2jwc, are you on macOS? dig, nslookup, etc aren't hooked up to the OS's dns system... for some reason.

Hi I know this is closed. I tested ping from the Ubuntu server itself that I have zeronsd running on.

ping shackpc.cahillnet.zt
ping: shackpc.cahillnet.zt: Name or service not known

dig +short @10.100.244.2 shackpc.cahillnet.zt
10.100.244.102

**Comment by laduke** [comment]
Sorry it's not working. It's not related to this topic either :) 
It sounds like the server is not set up to use that dns server for that domain. Good luck! 
https://github.com/zerotier/zeronsd#per-interface-dns-resolution
