### ISSUE TITLE
Multiple TLD support

### ISSUE THREAD

**Issue by LecrisUT** [zerotier/zeronsd#16]
The issue is self-explanatory.

**Comment by erikh** [comment]
I'm not sure I agree. Multiple TLDs implies some kind of partitioning and a rethinking of how the TLD is in relation to the individual addresses. How would you propose this be done?

Open to the idea, just disagree that's it's self-explanatory.

**Comment by LecrisUT** [comment]
Fair enough, what I wanted to say was supporting the ability to serve multiple TLDs, so that we can assign different TLDs to each machine. The application is mostly for simplifying split-view dns and organizations.

For an example, let's say we have some services that are available both publicly and privately, e.g. public website with private backend admin (gated by ip). So we would want the dns to override and serve us the private records for the website's dns name. Assuming the services are cnames to a sub-domain whose a records only we override. Now if we also want private only services on a local network and let's say it has a similar structure but on a private tld, it would be helpful to override the records when accessing via the same zero-tier network.

**Comment by erikh** [comment]
Sure, so here, on linux you can accomplish this really easily with systemd-networkd and systemd-resolved. If that's an option for you, try this package I slapped together over the weekend, I think it will really help. https://github.com/erikh/zerotier-systemd-manager

Windows and Mac OS X already do per-interface DNS resolution so you should be on solid ground there as long as you partition the TLD at the interface.

Does that help? I can do more here, happy to, but I would like to know why this isn't a solution before we discuss that.

**Comment by LecrisUT** [comment]
Oh, also on that note, forwarding other specific requests as well, e.g. `partner-company.tld` or more practically forwarding `company.tld` requests to a/the dns resolver on the internal network. I.e. because `company.tld` is not globally resolvable, but only `nodes.company.tld` is being overridden. You can think of the situation where we are connecting to multiple zero-tier networks, and we don't want one to interfere with the other.

**Comment by erikh** [comment]
we're not going to alter the forwarding of records at all. there are so many uncanny security problems there that I don't have enough space to address in a github comment.

I'm sorry, that you will need to resolve differently, maybe with a front-side cache or similar ilk.
