### ISSUE TITLE
Can't build on latest ArchLinux

### ISSUE THREAD

**Issue by ato2** [zerotier/zeronsd#167]
yay -q -S --needed --noconfirm zeronsd
............
Compiling zeronsd v0.3.1 (/tmp/makepkg/zeronsd/src/zeronsd-0.3.1)
Finished release [optimized] target(s) in 2m 22s
==> Starting check()...
Compiling zeronsd v0.3.1 (/tmp/makepkg/zeronsd/src/zeronsd-0.3.1)
Finished release [optimized] target(s) in 30.55s
Running unittests (target/release/deps/zeronsd-bcc0a7999e667f66)

running 9 tests
test tests::test_domain_or_default ... ok
test tests::test_central_token_panic - should panic ... ok
test tests::test_central_token ... ok
test tests::test_parse_ip_from_cidr ... ok
test tests::test_supervise_systemd_green ... ok
test tests::test_supervise_systemd_red ... ok
test tests::test_parse_hosts_duplicate ... ok
test tests::test_parse_hosts ... ok
test tests::test_parse_member_name ... ok

test result: ok. 9 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.08s

 Running unittests (target/release/deps/zeronsd-7c058f527eafd345)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

 Running tests/integration.rs (target/release/deps/integration-122264a811ad5c18)

running 14 tests
test sixplane::test_battery_single_domain_named ... FAILED
test sixplane::test_battery_single_domain ... FAILED
test all::test_hosts_file_reloading ... FAILED
test ipv4::test_battery_single_domain_named ... FAILED
test sixplane::test_battery_multi_domain_hosts_file ... FAILED
test rfc4193::test_battery_single_domain_named ... FAILED
test rfc4193::test_wildcard_central ... FAILED
test ipv4::test_battery_single_domain ... FAILED
test rfc4193::test_battery_single_domain ... FAILED
test ipv4::test_wildcard_central ... FAILED
test test_get_listen_ip ... FAILED
test rfc4193::test_battery_multi_domain_hosts_file ... FAILED
test all::test_battery_multi_domain_hosts_file ... FAILED
test sixplane::test_wildcard_central ... FAILED

failures:

---- sixplane::test_battery_single_domain_named stdout ----
thread 'sixplane::test_battery_single_domain_named' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

---- sixplane::test_battery_single_domain stdout ----
thread 'sixplane::test_battery_single_domain' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- all::test_hosts_file_reloading stdout ----
thread 'all::test_hosts_file_reloading' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- ipv4::test_battery_single_domain_named stdout ----
thread 'ipv4::test_battery_single_domain_named' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- sixplane::test_battery_multi_domain_hosts_file stdout ----
thread 'sixplane::test_battery_multi_domain_hosts_file' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- rfc4193::test_battery_single_domain_named stdout ----
thread 'rfc4193::test_battery_single_domain_named' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- rfc4193::test_wildcard_central stdout ----
thread 'rfc4193::test_wildcard_central' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- ipv4::test_battery_single_domain stdout ----
thread 'ipv4::test_battery_single_domain' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- rfc4193::test_battery_single_domain stdout ----
thread 'rfc4193::test_battery_single_domain' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- ipv4::test_wildcard_central stdout ----
thread 'ipv4::test_wildcard_central' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- test_get_listen_ip stdout ----
thread 'test_get_listen_ip' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- rfc4193::test_battery_multi_domain_hosts_file stdout ----
thread 'rfc4193::test_battery_multi_domain_hosts_file' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- all::test_battery_multi_domain_hosts_file stdout ----
thread 'all::test_battery_multi_domain_hosts_file' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44

---- sixplane::test_wildcard_central stdout ----
thread 'sixplane::test_wildcard_central' panicked at 'Please provide TOKEN in the environment: NotPresent', tests/service.rs:189:44
failures:
all::test_battery_multi_domain_hosts_file
all::test_hosts_file_reloading
ipv4::test_battery_single_domain
ipv4::test_battery_single_domain_named
ipv4::test_wildcard_central
rfc4193::test_battery_multi_domain_hosts_file
rfc4193::test_battery_single_domain
rfc4193::test_battery_single_domain_named
rfc4193::test_wildcard_central
sixplane::test_battery_multi_domain_hosts_file
sixplane::test_battery_single_domain
sixplane::test_battery_single_domain_named
sixplane::test_wildcard_central
test_get_listen_ip

test result: FAILED. 0 passed; 14 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

error: test failed, to rerun pass '--test integration'
==> ERROR: A failure occurred in check().
Aborting...
-> error making: zeronsd
/pub/Linux/ArchLinux/zetis/bin/install/zeronsd 1465.86s user 49.19s system 808% cpu 3:07.45 total

1 stud@e0 ~ % cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
IMAGE_ID=aui-console
IMAGE_VERSION=linux_5_16_15-0318

stud@e0 ~ % yay
:: Synchronizing package databases...
core is up to date
extra is up to date
community is up to date
:: Starting full system upgrade...
there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
-> Flagged Out Of Date AUR Packages: icdiff
there is nothing to d

**Comment by glimberg** [comment]
Issue should probably be raised over [here](https://aur.archlinux.org/packages/zeronsd)  as this is where the Arch AUR integration & scripting is done.

**Comment by erikh** [comment]
@devvick maintains these packages and may want to weigh in here; let's leave this open for now.

**Comment by erikh** [comment]
Nobody should need to run the integration tests on package build fwiw.

**Comment by devvick** [comment]
Build should be fixed now. Although I'm not an expert on Rust, so I'd appreciate any PRs if the PKGBUILD is still inadequate:
https://github.com/devvick/PKGBUILDs/blob/main/zeronsd/PKGBUILD

**Comment by erikh** [comment]
I'll be sure to look tonight. Thanks for looking into this!

**Comment by erikh** [comment]
should do it; just make sure it's not running the tests in the `tests/` dir and you should be good.

@ato2 if you'd like to confirm, that'd be really great. I'll close this ticket tomorrow if I don't hear back.

**Comment by erikh** [comment]
closing this as I think it's resolved. Please feel free to open if you feel otherwise, @ato2.
