### ISSUE TITLE
(Feature Request) Mechanism to Deploy Internal TLS/SSL Certs to ZeroTier Clients?

### ISSUE THREAD

**Issue by pldmgg** [zerotier/zeronsd#192]
I know this is probably a long ways away, but now that ZeroNS is right around the corner, it would be awesome if there could be a way to distribute internal certificates to ZeroTier clients. (I know this might be out of scope of the project, but it would be pretty awesome)

**Comment by erikh** [comment]
we've been batting around ideas in this regard but nothing yet. Stay tuned.

------- Original Message -------

**Comment by laduke** [comment]
I really want this too but it's not happening any time soon
