### ISSUE TITLE
Failed to start zeronsd

### ISSUE THREAD

**Issue by fenggwsx** [zerotier/zeronsd#195]
According to the quickstart, I have run the following commands:
```
sudo zeronsd supervise -t /var/lib/zerotier-one/token -w -d beyond.corp db64858fed303528
sudo systemctl start zeronsd-db64858fed303528
sudo systemctl enable zeronsd-db64858fed303528
```
However, when rebooting the machine(Ubuntu20.04 installed), I encountered an error that the service zeronsd-db64858fed303528 failed to start, and another service called zerotier-one started successfully.
So, what's wrong?

**Comment by laduke** [comment]
check `journalctl -u zeronsd-db64858fed303528`

**Comment by fenggwsx** [comment]
> check `journalctl -u zeronsd-db64858fed303528`

I have run this but it told me the service's start request repeated too quickly. Finally, I searched it on the Internet and got the answer at [https://www.suse.com/support/kb/doc/?id=000019750](https://www.suse.com/support/kb/doc/?id=000019750)

I just simply followed the guidance, wrote `StartLimitBurst=0` in `[Service]` section and solved it!

Thank you for helping me find the problem!

**Comment by laduke** [comment]
great job! 

can you post why it was failing in the first place, before the repeated too quickly errors, if you get a chance?

**Comment by unknown10777** [comment]
I got the same error here.
```
# /usr/bin/zeronsd start -t /var/lib/zerotier-one/zerotier_token -w -d 35 6ab565387a71a950
Sep 11 11:57:51.514  INFO zeronsd::init: Welcome to ZeroNS!
Error: Unexpected Response Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("my.zerotier.com")), port: None, path: "/api/v1/network/6ab565387a71a950", query: None, fragment: None }, status: 500, headers: {"connection": "keep-alive", "content-length": "124", "content-type": "application/json", "x-frame-options": "SAMEORIGIN", "x-ratelimit-limit": "20", "x-ratelimit-remaining": "18", "x-ratelimit-reset": "Sun, 11 Sep 2022 03:57:52 UTC", "via": "1.1 google, 1.1 varnish", "accept-ranges": "bytes", "date": "Sun, 11 Sep 2022 03:57:52 GMT", "x-served-by": "cache-tyo11947-TYO", "x-cache": "MISS", "x-cache-hits": "0", "x-timer": "S1662868672.156246,VS0,VE185", "strict-transport-security": "max-age=300"} }
```

> great job!
> 
> can you post why it was failing in the first place, before the "repeated too quickly errors", if you get a chance?
