### ISSUE TITLE
Client nodes can't access DNS

### ISSUE THREAD

**Issue by anthonyma94** [zerotier/zeronsd#198]
I have zeronsd installed on a parent server and it can access all nodes within its network via DNS. However, the children nodes cannot access each other with DNS. Am I supposed to install zeronsd on every client?

**Comment by laduke** [comment]
> Am I supposed to install zeronsd on every client?

No

Did you enable `allowDNS` on your clients? 

https://docs.zerotier.com/zeronsd/quickstart#install-zerotier

**Comment by laduke** [comment]
Closing because probably not a zeronsd issue. Let us know if it is, or if we can improve the docs.

**Comment by anthonyma94** [comment]
Yes it is, all of my clients have `allowDNS=1` on the network.

**Comment by anthonyma94** [comment]
They are almost all pis running Raspberry Pi OS (Debian 11), with 1 windows laptop. They have their firewalls disabled. I don't change any network settings except joining the ZeroTier network and setting `allowDNS=1`. I try to ping using the DNS address, `ping testing-pi.iot.local`, and `iot.local` is set in the network as the domain.

**Comment by laduke** [comment]
Should work on Windows. Linux needs more configuration to know about the DNS server. https://github.com/zerotier/zeronsd#per-interface-dns-resolution

**Comment by anthonyma94** [comment]
So I need to install zeronsd-systemd-manager on each Linux node, but not zeronsd?

**Comment by glimberg** [comment]
Correct. ZeroNSD is a DNS server. zerotier-systemd-manager is what configures the DNS settings on Linux systems.
