### ISSUE TITLE
Local name without domain

### ISSUE THREAD

**Issue by Markus275** [zerotier/zeronsd#219]
Is it possible to use the DNS without a Domain? So instead of https://Homecloud.home.arpa/ I just want to use https:/Homecloud/?

**Comment by erikh** [comment]
you can add this locally to your machine inside of /etc/resolv.conf, by adjusting the search​ or domain​ parameters. Check the file's manual pages for more information. Not quite sure how to do it on windows.

As for making the server do it? Not easily.
------- Original Message -------
