### ISSUE TITLE
No such file or directory(os error2) -  zeronsd docker on Synology 

### ISSUE THREAD

**Issue by mtnbrit** [zerotier/zeronsd#220]
Im getting Error: No such file or directory (os error 2) when launching the zeronsd docker container on my Synology has that has the zerotier-synology container running on it already. I used the ZEROTIER_CENTRAL_TOKEN environment variable to pass the token and used the execution cmd start -d my.corp <network>. ive also tried with no -d, just start and the network id, same result.
Ive also tried mounting a file from the nas filesystem to /token.txt and pass this on the cmd line as -t /token.txt. but I still just get the same error.

Should I need to set elevated permissions in order to bind to port 53? (ive tired both with and without with no change)

**Comment by anhdowastaken** [comment]
I think you miss this:
```
You also need to mount your authtoken.secret, which we use to talk to zerotier-one
```
https://moonstar-x.dev/server-setup/games/zerotier/#docker-compose

**Comment by mtnbrit** [comment]
Thanks for the tip, that was it. I was going on the info in the GitHub readme that states " (the secret) is auto-detected on multiple platforms including Linux". I guess its not auto-detected on multi-container docker.
