### ISSUE TITLE
wildcards?

### ISSUE THREAD

**Issue by laduke** [zerotier/zeronsd#24]
I have found myself wanting *.zt-my-id.example.com (and/or *.my-node-name.example.com)

So that I can have like `api.travis.example.com`, `static.travis.example.com`, `otherapp.travis.example.com` etc 

Maybe as flag to enable it or not.

**Comment by erikh** [comment]
I think I'm going to try implementing this soon as a extension to the hosts file, so it won't be dynamically updateable but will be administrator-only access. How do you feel about that?

**Comment by erikh** [comment]
closed by #75
