### ISSUE TITLE
Supervision support for OS X, Windows

### ISSUE THREAD

**Issue by erikh** [zerotier/zeronsd#43]
- [x] OS X
- [ ] Windows
- [ ] Others?

**Comment by jmuchovej** [comment]
i've put together a working `plist` file (for MacOS). i don't know `rust`, sadly, so i don't think i'll be able to contribute code – but here's the general architecture of said `plist` that should _at least_ get you started.

these files will go in `/Library/LaunchDaemons/<file>`. i set them up as `com.zerotier.nsd.NETWORKID.plist` – following the naming schema for ZeroTier One (`com.zerotier.one.plist`).
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key> <string>com.zerotier.nsd.NETWORKID</string>

    <key>ProgramArguments</key>
    <array>
      <string>/absolute/path/to/zeronsd</string>
      <string>start</string>
      <!-- every space in the command appears to need a `<string> ... </string>` block -->
      <string>-t</string>
      <string>/absolute/path/to/token</string>
      <string>-d</string>
      <string>DOMAIN</string>
      <string>NETWORKID</string>
    </array>

    <key>UserName</key> <string>root</string>

    <key>RunAtLoad</key> <true/>

    <key>KeepAlive</key> <true/>

    <key>StandardErrorPath</key> <string>/var/log/zerotier/nsd/NETWORKID.err</string>
    <key>StandardOutPath</key> <string>/var/log/zerotier/nsd/NETWORKID.log</string>

  </dict>
</plist>
```

also, here's the manpage for [`plist`][man] in case you don't have MacOS.

i have two networks running this way and everything is hunky dory.

[man]: https://manpagez.com/man/5/launchd.plist/

**Comment by erikh** [comment]
Thanks! This is incredibly useful. Yeah, I don't have a mac here but other coworkers do, I will turn them into lab rats! I will circle back when I have something of value; probably in a few days.

**Comment by jmuchovej** [comment]
looks like this is good to go for MacOS? (also, i you misspelled my github username on the release. 🙂 )

**Comment by erikh** [comment]
kinda. We need to do homebrew packaging and the windows build was affected by this change so I need to adjust that a little bit. Expect 0.2.1 to land soon.

Sorry about the name; I'll fix it in the 0.2.1 announcement.

**Comment by jmuchovej** [comment]
not sure if this is helpful, but it seems like both of these are relevant to getting a service developed/installed in windows.
- https://docs.microsoft.com/en-us/dotnet/framework/windows-services/
- https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-create-windows-services

i _might_ have some time to take a crack at this, but i'm also not too keen on installed visual studio. 😅 (this would be the only reason for me to install it. 😞)

**Comment by erikh** [comment]
I was looking at some rust stuff to do this, namely centered around the `sc` tool. I haven't read the URLs above yet; I will try to get to it today.

**Comment by erikh** [comment]
Since the windows stuff is still well-outstanding I'm going to close this ticket since we have enough of a result.
