### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jmuchovej** [zerotier/zeronsd#82]
(maybe this should be placed elsewhere, but i figured i'd open here.)

i recently had to switch over a windows machine for daily driving, so i was hoping to pick up using ZeroNS in the meantime.

so far, i've been able to **install** and **start** ZeroNS, but `ping` and `nslookup` both fail to resolve. i'm not too sure how to do logging/whatnot on windows, but i'm opening this to essentially report i'm a ready and willing test subject for ZeroNS on windows. 😂

**Comment by erikh** [comment]
@jmuchovej so this is a sticky bit with OS X and Windows. Two things you need to know:

- some systems tools (nslookup is a big offender, but ping *should* work) won't work
- PTR records won't resolve at all right now. We have an open internal issue for that, I hope to get it in before ZeroTier's next release rolls out.

Try passing multiples of the `-v` flag to zeronsd's windows binary. I'll try to do some testing today as well.

**Comment by erikh** [comment]
Also, mind the windows firewall. It's a thing.

**Comment by erikh** [comment]
Sorry I'll comment one more time and be done. Generally, when debugging DNS, you can follow these fast & loose rules:

- if the response is fast and incorrect, you have either the wrong dns server or a poorly configured one
- if the response is slow, your dns server is not responding to requests.

Hope this is useful.

**Comment by erikh** [comment]
@jmuchovej so it seems this ticket and #88 have a lot in common. I'm debugging this and it's definitely the firewall, but i want to collapse this into a single ticket. This ticket will be closed since @glimberg has some additional flavor on that one.

I'm sorry it's taken a while to get to this.
