### ISSUE TITLE
docker: Allow zeronsd to be passed configuration

### ISSUE THREAD

**Issue by e-hollebone** [zerotier/zeronsd#86]
I am running zerosnd on an Unraid server using the docker container but the default container setup does not execute directly out of the box.  I currently work around this by using portainer to update the cmd arg to be

/bin/sh -c '/usr/bin/zeronsd 'start XXXXXXXXXXXXXXXX -d "XXXX.hollebone.ca"' and overriding the entry point to null.

My issue is every time the container is updated/recreated, I have to manually update the container entry point.  I would like to request an enhancement that would allow the configuration to be pass into the docker container either as environment variables or by config file. A possible path could be to have zerosnd to use environment variables for all the cmd line args ie. network and domain etc. like it does for the ZEROTIER_CENTRAL_TOKEN

**Comment by erikh** [comment]
You shouldn't need to update the entrypoint at all. Why are you doing that?

**Comment by erikh** [comment]
Sorry, I didn't mean to sound rude to you, hope it didn't come off that way. Here's a longer answer:

The entrypoint in the docker image is `/usr/bin/zeronsd` and should take arguments to it as the CMD section of the docker image. This means that your arguments will look something like:

`start <network id> -d <domain>`

as opposed to what you might be expecting which is:

`/usr/bin/zeronsd start <network id> -d <domain>`

I'm not familiar with unraid, but if it's using docker-compose or kubernetes under the hood, this is almost certainly the issue.

**Comment by erikh** [comment]
also important is that these arguments must be expressed as an _array_, as the shell is not used at all.

**Comment by e-hollebone** [comment]
No rudeness observed. Was just suggesting how it might make the service better in non-standard use-cases. All good on that front. 

Just as an FYI, Unraid (Slackware-based Storage OS with VM and Docker support) basically creates an XML template of the docker-compose with automation features (prioritized start order, automatic fetch and update, cpu pinning etc).  

And I understand if Unraid support might be considered niche or too small a slice of the overall population to support, that would be a completely fair assessment.

Secondly, I won't claim that have a deep knowledge of docker. I am an engaged amateur at best and through my hacking, I have been able to get Zeronsnd running in unraid/docker, so if this issue might be solved another way, I am all ears.

**Comment by erikh** [comment]
Ok. Yeah, I think at least for now it'd be better if we got these contributions from the community on that front. I'm fairly certain you can work with the existing image regardless, fwiw; you'll just want to specify the "command" as a argument array, not a string you pass to a shell.

In the event you really really want to do that anyways, try this dockerfile:

```Dockerfile
FROM zerotier/zeronsd

ENTRYPOINT []
CMD []
```

which should clean up all this balleyhoo and leave you at a shell; then you can work it out however you'd like.

HTH, will leave this ticket open for now, but will probably close this if this is a working solution for you.

**Comment by erikh** [comment]
So I want to be clear, I'm leaving this open because we will (and are starting ground work on things that need them) need configuration soon, and I want to communicate that we will have support for this in the upcoming months. I did kind of fly past your initial suggestion because it's a thing we've discussed internally a few times and I apologize for that.

It's being thought about and eventually, I will likely replace this ticket with a feature ticket describing how to do it, I just wanted to make sure you were affirmed on that front.

**Comment by e-hollebone** [comment]
Thanks Erik. Honestly, I am just happy you are still considering it as a future enhancement. I have a functional workaround through the manual override of the docker entry point and can continue to do so as the software evolves.

Cheers,
Eric

**Comment by erikh** [comment]
This is resolved in the next release.
