### ISSUE TITLE
can't resolve from linux (and openwrt)

### ISSUE THREAD

**Issue by fragolinux** [zerotier/zeronsd#95]
hi, i'm trying to setup this in a bunch of my linux boxes... i set up the dns "server" part on a cloud vps, and from windows pc (after adding the allowdns checkbox) i can ping them all now... same from the cloud dns itself...

but no one of the linux boxes can resolve the other devices name... i did the **zerotier-cli set net-id allowdns=1**, i see that **zerotier-cli get net-id allowdns** reports 1, and  **zerotier-cli  listnetworks -j** too, restarted the daemon, the full linux box itself, too, but nothing, they can't resolve any host on my zt network... what am i missing?

also, how to enable this in openwrt? what to add to /etc/config/zerotier file, or which other if not this?

ALL of my systems are at latest 1.6.5 version

thanks

**Comment by laduke** [comment]
allowDNS doesn't do anything on linux. There are too many ways to set up linux networking, so zerotier doesn't do it (yet?)

you can check this out for systemd based systems https://github.com/zerotier/zerotier-systemd-manager

No idea how you'd do per interface dns on openwrt

**Comment by erikh** [comment]
You may not be able to if it doesn't support systemd-networkd.

Thanks for getting to this Travis, I had forgotten about it.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by erikh** [comment]
@fragolinux I don't know how openwrt does networking these days; I haven't used it for some time, sorry.

However, zeronsd depends on the per-interface resolution feature of other operating systems, something systemd-networkd can do via system-resolved. The tool that @laduke referred to adjusts the settings of systemd-resolved to match your network settings in zerotier.

An alternative is to just flat out make your zeronsd your main resolver in resolv.conf; it will use the resolver rules of the resolv.conf zeronsd is living on, so you can use it kind of like dnsmasq if you wanted to.

I hope this helps. I'm going to close this ticket as I don't really see a bug here, just a misunderstanding of how to use the tool. I hope you are satisfied; please feel free to reopen if you have more questions.
