### ISSUE TITLE
[Feature Request} add hosts to dns without appending the domain

### ISSUE THREAD

**Issue by Codel1417** [zerotier/zeronsd#98]
basically i want to route the tld to a zt host, but a hosts entry of example.com becomes example.com.example.com

**Comment by erikh** [comment]
There’s another ticket similar to this, but I can’t see dynamic serving off the root playing well with trust dns’s architecture (easily, at least) or dns in general. There are also numerous attack problems with this approach that I honestly don’t feel qualified to fully assess, much less list.

I don’t see this working. A set of zones for tlds would work, but there is more to do from a UX perspective before I think that’s realistic. If that’s what you really want, I can bring it up to the team at a future point.

**Comment by Codel1417** [comment]
I was thinking of just specifying a zt device, either as a separate hosts file or a launch option. The root would be explicitly set to prevent an unexpected device from taking over a tld.

**Comment by erikh** [comment]
let me know how it goes. I think the fundamental problem here is that you'll need to either forward or manage dns in a much more pedantic way than zeronsd does currently (which is, program a zone and then give it to trust dns to work with), and I don't think it's necessarily worth the effort, at least at this point in the game. wildcard support would also need to be managed delicately.

If you find an easier solution I'd love to hear about it; but no guarantees on a merge. I worry this brings a lot of extra complexity with few wins. I hope you can understand my viewpoint.
